#!/usr/bin/env node

// Converts astrometry.net's stellarium-constellations.c into the GeoJSON
// FeatureCollection shape used by data/nightsky/constellations.lines.json,
// so the night-sky renderer can consume either dataset without changes.
//
// Usage: node scripts/convertAstrometryConstellations.js <path-to-stellarium-constellations.c>
//
// The input file is part of astrometry.net (dstndstn/astrometry.net,
// catalogs/stellarium-constellations.c). Astrometry.net asserts that its
// authored code is licensed under 3-clause BSD; the file is generated by
// catalogs/grab-stellarium-constellations.c from Stellarium's default
// "Western" skyculture asterisms.

const fs = require("fs");
const path = require("path");

function die(msg) {
    console.error(msg);
    process.exit(1);
}

const inputArg = process.argv[2];
if (!inputArg) die("Usage: node convertAstrometryConstellations.js <stellarium-constellations.c>");
const src = fs.readFileSync(inputArg, "utf-8");

// shortnames[] = {"Aql","And", ...};
const shortnamesMatch = src.match(/static const char\* shortnames\[\]\s*=\s*\{([^}]*)\}/);
if (!shortnamesMatch) die("Could not locate shortnames[] array");
const shortnames = [...shortnamesMatch[1].matchAll(/"([^"]+)"/g)].map(m => m[1]);

// star_positions[] = {2.09654, 29.0908, ...};
const starsMatch = src.match(/static const double star_positions\[\]\s*=\s*\{([^}]*)\}/);
if (!starsMatch) die("Could not locate star_positions[] array");
const flatStars = starsMatch[1].split(",").map(s => s.trim()).filter(s => s.length);
if (flatStars.length % 2 !== 0) die(`star_positions length ${flatStars.length} is not even`);
const stars = [];
for (let i = 0; i < flatStars.length; i += 2) {
    stars.push([Number(flatStars[i]), Number(flatStars[i + 1])]);
}

// constellation_lines_N[] = {idx, idx, idx, idx, ...};
const lineArrays = [];
const lineRe = /static const int constellation_lines_(\d+)\[\]\s*=\s*\{([^}]*)\}/g;
let m;
while ((m = lineRe.exec(src)) !== null) {
    const idx = Number(m[1]);
    const values = m[2].split(",").map(s => s.trim()).filter(s => s.length).map(Number);
    if (values.length % 2 !== 0) die(`constellation_lines_${idx} has odd length ${values.length}`);
    lineArrays[idx] = values;
}

if (lineArrays.length !== shortnames.length) {
    die(`Got ${lineArrays.length} line arrays but ${shortnames.length} shortnames`);
}

const features = [];
for (let i = 0; i < shortnames.length; i++) {
    const indices = lineArrays[i];
    const coordinates = [];
    for (let j = 0; j < indices.length; j += 2) {
        const a = stars[indices[j]];
        const b = stars[indices[j + 1]];
        if (!a || !b) die(`Constellation ${shortnames[i]}: out-of-range star index ${indices[j]} or ${indices[j + 1]}`);
        coordinates.push([a, b]);
    }
    features.push({
        type: "Feature",
        id: shortnames[i],
        properties: { rank: "1" },
        geometry: { type: "MultiLineString", coordinates },
    });
}

const out = {
    type: "FeatureCollection",
    _source: "Derived from astrometry.net's catalogs/stellarium-constellations.c (BSD-3-Clause). " +
             "Upstream asterism conventions come from Stellarium's default 'Western' skyculture.",
    features,
};

const outPath = path.resolve(__dirname, "..", "data", "nightsky", "constellations.lines.astrometry.json");
fs.writeFileSync(outPath, JSON.stringify(out));
console.log(`Wrote ${outPath}`);
console.log(`  ${features.length} constellations, ${stars.length} stars, ` +
    `${features.reduce((n, f) => n + f.geometry.coordinates.length, 0)} segments`);
